# Generated by Django 4.1 on 2022-08-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='name',
            new_name='name_authors',
        ),
    ]
